// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL (session mode, port 5432) for migrations and schema operations
    // pgBouncer (transaction mode, port 6543) doesn't support required operations
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
